# Generated by Django 3.1.12 on 2023-10-14 03:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_sliders_colorbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='colorBackground',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=25, samples=None),
        ),
    ]
