# Generated by Django 3.1.12 on 2023-10-24 15:49

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sliders_colorbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/aboutus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sliders',
            name='colorBackground',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(upload_to='static/img/sliders'),
        ),
    ]
