# Generated by Django 3.1.12 on 2023-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231024_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/logo')),
            ],
        ),
    ]
