# Generated by Django 3.1.12 on 2023-11-11 07:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_logos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footers',
            old_name='link_blibli',
            new_name='link_padiumkm',
        ),
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(upload_to='static/img/sliders', validators=[home.models.validate_file_size]),
        ),
    ]
